version: '3.8'
services:
  db:
    image: postgres:15 
    container_name: volunteerdb_db
    environment:
      POSTGRES_DB: volunteerdb
      POSTGRES_USER: volunteeruser
      POSTGRES_PASSWORD: volunteerpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: